# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/iam_db
spring.datasource.username=admin
spring.datasource.password=password123
spring.jpa.hibernate.ddl-auto=update

# Configuração das chaves RSA
rsa.public-key=classpath:certs/public.pem
rsa.private-key=classpath:certs/private.pem

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379